// Generates scripts/seed.sql — participants + trip from the Japan Nov/Dec 2026 documents,
// plus the first admin account. Run `npm run seed:gen` then `npm run db:local` / `db:remote`.
import { pbkdf2Sync, randomBytes } from 'node:crypto';
import { writeFileSync } from 'node:fs';

const ADMIN_EMAIL = process.env.ADMIN_EMAIL ?? 'admin@jelajah.local';
const ADMIN_NAME = process.env.ADMIN_NAME ?? 'Admin';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD ?? 'ubah-saya-123';

const salt = randomBytes(16);
const hash = pbkdf2Sync(ADMIN_PASSWORD, salt, 100000, 32, 'sha256');

// 15 adults + 1 infant, exactly as they appear across the Trip.com bookings
const participants = [
  ['Mohd Ismail Ismail Bin Hassim', 0],
  ['Mashuraizzah Binti Mustapha', 0],
  ['Hairuni Binti Hassim', 0],
  ['Hamizan Bin Hamdani', 0],
  ['Kairi Ashraf Bin Kamarolzeman', 0],
  ['Kamarolzeman Bin Mohamad Mustapha', 0],
  ['Muhammad Nur Iskandar Bin Ismail', 0],
  ['Nurul Ain Binti Hamizan', 0],
  ['Jalita Binti Junaidi', 0],
  ['Hamzah Bin Hamizan', 0],
  ['Haziqah Binti Hassan', 0],
  ['Ranizah Binti Rahbi', 0],
  ['Jadirah Azra Binti Kamarolzeman', 0],
  ['Mohammad Indera Bin Zamri', 0],
  ['Mohammad Namazi Bin Salleh', 0],
  ['Hareth Azran Bin Hamzah', 1],
];

const q = s => `'${String(s).replace(/'/g, "''")}'`;
let sql = `-- Generated by scripts/seed.mjs\n`;
participants.forEach(([name, infant], i) => {
  sql += `INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (${i + 1}, ${q(name)}, ${infant});\n`;
});
sql += `INSERT OR IGNORE INTO trips (id, name, destination, start_date, end_date, emoji)
VALUES (1, 'Jelajah Jepun 2026', 'Tokyo & Osaka, Japan', '2026-11-29', '2026-12-07', '🇯🇵');\n`;
participants.forEach((_, i) => {
  sql += `INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, ${i + 1});\n`;
});
sql += `INSERT OR IGNORE INTO users (id, email, name, password_hash, salt, role, must_change_password)
VALUES (1, ${q(ADMIN_EMAIL)}, ${q(ADMIN_NAME)}, ${q(hash.toString('base64'))}, ${q(salt.toString('base64'))}, 'admin', 1);\n`;

writeFileSync('scripts/seed.sql', sql);
console.log(`scripts/seed.sql written. Admin login: ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}`);
