-- Generated by scripts/seed.mjs
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (1, 'Mohd Ismail Ismail Bin Hassim', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (2, 'Mashuraizzah Binti Mustapha', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (3, 'Hairuni Binti Hassim', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (4, 'Hamizan Bin Hamdani', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (5, 'Kairi Ashraf Bin Kamarolzeman', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (6, 'Kamarolzeman Bin Mohamad Mustapha', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (7, 'Muhammad Nur Iskandar Bin Ismail', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (8, 'Nurul Ain Binti Hamizan', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (9, 'Jalita Binti Junaidi', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (10, 'Hamzah Bin Hamizan', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (11, 'Haziqah Binti Hassan', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (12, 'Ranizah Binti Rahbi', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (13, 'Jadirah Azra Binti Kamarolzeman', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (14, 'Mohammad Indera Bin Zamri', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (15, 'Mohammad Namazi Bin Salleh', 0);
INSERT OR IGNORE INTO participants (id, name, is_infant) VALUES (16, 'Hareth Azran Bin Hamzah', 1);
INSERT OR IGNORE INTO trips (id, name, destination, start_date, end_date, emoji)
VALUES (1, 'Jelajah Jepun 2026', 'Tokyo & Osaka, Japan', '2026-11-29', '2026-12-07', '🇯🇵');
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 1);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 2);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 3);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 4);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 5);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 6);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 7);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 8);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 9);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 10);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 11);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 12);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 13);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 14);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 15);
INSERT OR IGNORE INTO trip_members (trip_id, participant_id) VALUES (1, 16);
INSERT OR IGNORE INTO users (id, email, name, password_hash, salt, role, must_change_password)
VALUES (1, 'admin@jelajah.local', 'Admin', 'JBx3WqW4IgfL6WZX/sXICjnTPx0OssbAnIa9Cbk1dv4=', 'XxEDk9LgIKlUL67HzV71lg==', 'admin', 1);
